// components/Skills.vue
<template lang="pug">
  .skills.o-container(v-if="skills")
    h2.heading
      .outline {{ skills.heading }}
      .solid {{ skills.heading }}
    div(v-for="section in skills.preference" :key="section.heading")
      h3.subheading {{ section.heading }}
      ul.skill-list
        li.skill(v-for="skill in section.list" :key="skill.language") {{ skill.language }}
</template>

<script>
export default {
  props: {
    skills: {
      type: Object,
      default() {
        return {}
      },
    },
  },
}
</script>

<style lang="scss" scoped>
.subheading {
  font-family: $inter;
  font-weight: 500;
}
.skill-list {
  margin-bottom: 3.2rem;
  margin-left: -0.8rem;
  margin-top: -0.8rem;
  padding-top: 0.8rem;
}

.skill {
  @extend %label;
  background-color: darken($cotton, 5%);
  display: inline-block;
  margin-left: 0.8rem;
  margin-top: 0.8rem;
  padding: 0.75rem 1rem;
  user-select: none;
}
</style>

// src/components/skills.tsx
import s from './skills.module.scss'

export default function Skills({skills}: {skills: any}) {
  return (
    <section className="o-container">
      <h2 className="heading">
        <div className="outline">{skills.heading}</div>
        <div className="solid">{skills.heading}</div>
      </h2>
      {skills.preference.map((group: any) => (
        <div key={skills.language}>
          <h3 className={s.subheading}>{group.heading}</h3>
          <ul className={s.skillList}>
            {group.list.map((skill: any) => (
              <li className={s.skill} key={skill.language}>
                <span>{skill.language}</span>
              </li>
            ))}
          </ul>
        </div>

      ))}
    </section>
  )
}
